package hangul

// Hangul Jamo. Range 1100-11FF
const (
	LEAD_BASE   = 0x1100 // HANGUL CHOSEONG KIYEOK
	MEDIAL_BASE = 0x1161 // HANGUL JUNGSEONG A
	TAIL_BASE   = 0x11A8 // HANGUL JONGSEONG KIYEOK
)

// Initial consonants 초성
const (
	_       = (LEAD_BASE - 1) + iota
	LEAD_G  // HANGUL CHOSEONG KIYEOK
	LEAD_GG // HANGUL CHOSEONG SSANGKIYEOK
	LEAD_N  // HANGUL CHOSEONG NIEUN
	LEAD_D  // HANGUL CHOSEONG TIKEUT
	LEAD_DD // HANGUL CHOSEONG SSANGTIKEUT
	LEAD_R  // HANGUL CHOSEONG RIEUL
	LEAD_M  // HANGUL CHOSEONG MIEUM
	LEAD_B  // HANGUL CHOSEONG PIEUP
	LEAD_BB // HANGUL CHOSEONG SSANGPIEUP
	LEAD_S  // HANGUL CHOSEONG SIOS
	LEAD_SS // HANGUL CHOSEONG SSANGSIOS
	LEAD_ZS // HANGUL CHOSEONG IEUNG (zero sound)
	LEAD_J  // HANGUL CHOSEONG CIEUC
	LEAD_JJ // HANGUL CHOSEONG SSANGCIEUC
	LEAD_C  // HANGUL CHOSEONG CHIEUCH
	LEAD_K  // HANGUL CHOSEONG KHIEUKH
	LEAD_T  // HANGUL CHOSEONG THIEUTH
	LEAD_P  // HANGUL CHOSEONG PHIEUPH
	LEAD_H  // HANGUL CHOSEONG HIEUH
)
const MAX_LEAD_IDX = LEAD_H - LEAD_G

// Medial vowels 중성
const (
	_          = (MEDIAL_BASE - 1) + iota
	MEDIAL_A   // HANGUL JUNGSEONG A
	MEDIAL_AE  // HANGUL JUNGSEONG AE
	MEDIAL_YA  // HANGUL JUNGSEONG YA
	MEDIAL_YAE // HANGUL JUNGSEONG YAE
	MEDIAL_EO  // HANGUL JUNGSEONG EO
	MEDIAL_E   // HANGUL JUNGSEONG E
	MEDIAL_YEO // HANGUL JUNGSEONG YEO
	MEDIAL_YE  // HANGUL JUNGSEONG YE
	MEDIAL_O   // HANGUL JUNGSEONG O
	MEDIAL_WA  // HANGUL JUNGSEONG WA
	MEDIAL_WAE // HANGUL JUNGSEONG WAE
	MEDIAL_OE  // HANGUL JUNGSEONG OE
	MEDIAL_YO  // HANGUL JUNGSEONG YO
	MEDIAL_U   // HANGUL JUNGSEONG U
	MEDIAL_WEO // HANGUL JUNGSEONG WEO
	MEDIAL_WE  // HANGUL JUNGSEONG WE
	MEDIAL_WI  // HANGUL JUNGSEONG WI
	MEDIAL_YU  // HANGUL JUNGSEONG YU
	MEDIAL_EU  // HANGUL JUNGSEONG EU
	MEDIAL_YI  // HANGUL JUNGSEONG YI
	MEDIAL_I   // HANGUL JUNGSEONG I
)
const MAX_MEDIAL_IDX = MEDIAL_I - MEDIAL_A

// Final consonants 종성
const (
	_       = (TAIL_BASE - 1) + iota
	TAIL_G  // HANGUL JONGSEONG KIYEOK
	TAIL_GG // HANGUL JONGSEONG SSANGKIYEOK
	TAIL_GS // HANGUL JONGSEONG KIYEOK-SIOS
	TAIL_N  // HANGUL JONGSEONG NIEUN
	TAIL_NJ // HANGUL JONGSEONG NIEUN-CIEUC
	TAIL_NH // HANGUL JONGSEONG NIEUN-HIEUH
	TAIL_D  // HANGUL JONGSEONG TIKEUT
	TAIL_L  // HANGUL JONGSEONG RIEUL
	TAIL_LG // HANGUL JONGSEONG RIEUL-KIYEOK
	TAIL_LM // HANGUL JONGSEONG RIEUL-MIEUM
	TAIL_LB // HANGUL JONGSEONG RIEUL-PIEUP
	TAIL_LS // HANGUL JONGSEONG RIEUL-SIOS
	TAIL_LT // HANGUL JONGSEONG RIEUL-THIEUTH
	TAIL_LP // HANGUL JONGSEONG RIEUL-PHIEUPH
	TAIL_LH // HANGUL JONGSEONG RIEUL-HIEUH
	TAIL_M  // HANGUL JONGSEONG MIEUM
	TAIL_B  // HANGUL JONGSEONG PIEUP
	TAIL_BS // HANGUL JONGSEONG PIEUP-SIOS
	TAIL_S  // HANGUL JONGSEONG SIOS
	TAIL_SS // HANGUL JONGSEONG SSANGSIOS
	TAIL_NG // HANGUL JONGSEONG IEUNG
	TAIL_J  // HANGUL JONGSEONG CIEUC
	TAIL_C  // HANGUL JONGSEONG CHIEUCH
	TAIL_K  // HANGUL JONGSEONG KHIEUKH
	TAIL_T  // HANGUL JONGSEONG THIEUTH
	TAIL_P  // HANGUL JONGSEONG PHIEUPH
	TAIL_H  // HANGUL JONGSEONG HIEUH
)
const MAX_TAIL_IDX = TAIL_H - TAIL_G
