package hangul

// Hangul Compatibility Jamo. Range: 3130-318F
const (
	_   = 0x3130 + iota
	G   // HANGUL LETTER KIYEOK
	GG  // HANGUL LETTER SSANGKIYEOK
	GS  // HANGUL LETTER KIYEOK-SIOS
	N   // HANGUL LETTER NIEUN
	NJ  // HANGUL LETTER NIEUN-CIEUC
	NH  // HANGUL LETTER NIEUN-HIEUH
	D   // HANGUL LETTER TIKEUT
	DD  // HANGUL LETTER SSANGTIKEUT
	L   // HANGUL LETTER RIEUL
	LG  // HANGUL LETTER RIEUL-KIYEOK
	LM  // HANGUL LETTER RIEUL-MIEUM
	LB  // HANGUL LETTER RIEUL-PIEUP
	LS  // HANGUL LETTER RIEUL-SIOS
	LT  // HANGUL LETTER RIEUL-THIEUTH
	LP  // HANGUL LETTER RIEUL-PHIEUPH
	LH  // HANGUL LETTER RIEUL-HIEUH
	M   // HANGUL LETTER MIEUM
	B   // HANGUL LETTER PIEUP
	BB  // HANGUL LETTER SSANGPIEUP
	BS  // HANGUL LETTER PIEUP-SIOS
	S   // HANGUL LETTER SIOS
	SS  // HANGUL LETTER SSANGSIOS
	ZS  // HANGUL LETTER IEUNG (zero sound)
	J   // HANGUL LETTER CIEUC
	JJ  // HANGUL LETTER SSANGCIEUC
	C   // HANGUL LETTER CHIEUCH
	K   // HANGUL LETTER KHIEUKH
	T   // HANGUL LETTER THIEUTH
	P   // HANGUL LETTER PHIEUPH
	H   // HANGUL LETTER HIEUH
	A   // HANGUL LETTER A
	AE  // HANGUL LETTER AE
	YA  // HANGUL LETTER YA
	YAE // HANGUL LETTER YAE
	EO  // HANGUL LETTER EO
	E   // HANGUL LETTER E
	YEO // HANGUL LETTER YEO
	YE  // HANGUL LETTER YE
	O   // HANGUL LETTER O
	WA  // HANGUL LETTER WA
	WAE // HANGUL LETTER WAE
	OE  // HANGUL LETTER OE
	YO  // HANGUL LETTER YO
	U   // HANGUL LETTER U
	WEO // HANGUL LETTER WEO
	WE  // HANGUL LETTER WE
	WI  // HANGUL LETTER WI
	YU  // HANGUL LETTER YU
	EU  // HANGUL LETTER EU
	YI  // HANGUL LETTER YI
	I   // HANGUL LETTER I
	NG  = ZS
)

// Hangul Jamo. Range 1100-11FF
const (
	leadBase   = 0x1100 // HANGUL CHOSEONG KIYEOK
	medialBase = 0x1161 // HANGUL JUNGSEONG A
	tailBase   = 0x11A8 // HANGUL JONGSEONG KIYEOK
)

// Initial consonants 초성
const (
	_      = (leadBase - 1) + iota
	LeadG  // HANGUL CHOSEONG KIYEOK
	LeadGG // HANGUL CHOSEONG SSANGKIYEOK
	LeadN  // HANGUL CHOSEONG NIEUN
	LeadD  // HANGUL CHOSEONG TIKEUT
	LeadDD // HANGUL CHOSEONG SSANGTIKEUT
	LeadR  // HANGUL CHOSEONG RIEUL
	LeadM  // HANGUL CHOSEONG MIEUM
	LeadB  // HANGUL CHOSEONG PIEUP
	LeadBB // HANGUL CHOSEONG SSANGPIEUP
	LeadS  // HANGUL CHOSEONG SIOS
	LeadSS // HANGUL CHOSEONG SSANGSIOS
	LeadZS // HANGUL CHOSEONG IEUNG (zero sound)
	LeadJ  // HANGUL CHOSEONG CIEUC
	LeadJJ // HANGUL CHOSEONG SSANGCIEUC
	LeadC  // HANGUL CHOSEONG CHIEUCH
	LeadK  // HANGUL CHOSEONG KHIEUKH
	LeadT  // HANGUL CHOSEONG THIEUTH
	LeadP  // HANGUL CHOSEONG PHIEUPH
	LeadH  // HANGUL CHOSEONG HIEUH
)
const maxLeadIdx = LeadH - LeadG

// Medial vowels 중성
const (
	_         = (medialBase - 1) + iota
	MedialA   // HANGUL JUNGSEONG A
	MedialAE  // HANGUL JUNGSEONG AE
	MedialYA  // HANGUL JUNGSEONG YA
	MedialYAE // HANGUL JUNGSEONG YAE
	MedialEO  // HANGUL JUNGSEONG EO
	MedialE   // HANGUL JUNGSEONG E
	MedialYEO // HANGUL JUNGSEONG YEO
	MedialYE  // HANGUL JUNGSEONG YE
	MedialO   // HANGUL JUNGSEONG O
	MedialWA  // HANGUL JUNGSEONG WA
	MedialWAE // HANGUL JUNGSEONG WAE
	MedialOE  // HANGUL JUNGSEONG OE
	MedialYO  // HANGUL JUNGSEONG YO
	MedialU   // HANGUL JUNGSEONG U
	MedialWEO // HANGUL JUNGSEONG WEO
	MedialWE  // HANGUL JUNGSEONG WE
	MedialWI  // HANGUL JUNGSEONG WI
	MedialYU  // HANGUL JUNGSEONG YU
	MedialEU  // HANGUL JUNGSEONG EU
	MedialYI  // HANGUL JUNGSEONG YI
	MedialI   // HANGUL JUNGSEONG I
)
const maxMedialIdx = MedialI - MedialA

// Final consonants 종성
const (
	_      = (tailBase - 1) + iota
	TailG  // HANGUL JONGSEONG KIYEOK
	TailGG // HANGUL JONGSEONG SSANGKIYEOK
	TailGS // HANGUL JONGSEONG KIYEOK-SIOS
	TailN  // HANGUL JONGSEONG NIEUN
	TailNJ // HANGUL JONGSEONG NIEUN-CIEUC
	TailNH // HANGUL JONGSEONG NIEUN-HIEUH
	TailD  // HANGUL JONGSEONG TIKEUT
	TailL  // HANGUL JONGSEONG RIEUL
	TailLG // HANGUL JONGSEONG RIEUL-KIYEOK
	TailLM // HANGUL JONGSEONG RIEUL-MIEUM
	TailLB // HANGUL JONGSEONG RIEUL-PIEUP
	TailLS // HANGUL JONGSEONG RIEUL-SIOS
	TailLT // HANGUL JONGSEONG RIEUL-THIEUTH
	TailLP // HANGUL JONGSEONG RIEUL-PHIEUPH
	TailLH // HANGUL JONGSEONG RIEUL-HIEUH
	TailM  // HANGUL JONGSEONG MIEUM
	TailB  // HANGUL JONGSEONG PIEUP
	TailBS // HANGUL JONGSEONG PIEUP-SIOS
	TailS  // HANGUL JONGSEONG SIOS
	TailSS // HANGUL JONGSEONG SSANGSIOS
	TailNG // HANGUL JONGSEONG IEUNG
	TailJ  // HANGUL JONGSEONG CIEUC
	TailC  // HANGUL JONGSEONG CHIEUCH
	TailK  // HANGUL JONGSEONG KHIEUKH
	TailT  // HANGUL JONGSEONG THIEUTH
	TailP  // HANGUL JONGSEONG PHIEUPH
	TailH  // HANGUL JONGSEONG HIEUH
)
const maxTailIdx = TailH - TailG
